name: BugFixes
main: de.lukas.bugfixes.BugFixes
version: 0.0.11a

commands:
  sysinfos:
    usage: /sysinfos
  delentities:
    usage: /delentities
  countentities:
    usage: /countentities
  cleanup:
    usage: /cleanup
  bugfixes:
    usage: /bugfixes
    
